# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  #- docker login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-npm
  - npm i -g heroku

deploy-develop:
  stage: deploy
  script:
    - docker run -t -v $PWD:/app --workdir /app mcr.microsoft.com/dotnet/core/sdk:3.1 bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"
    - docker build -t $CI_REGISTRY/my-awesome-app-dev/web .
    - docker push $CI_REGISTRY/my-awesome-app-dev/web
    # above two commands can be replaced with: "heroku container:push web --app my-awesome-app-dev"
    - heroku container:release web --app my-awesome-app-dev
  only:
    - develop
